Server:
  RunMode: debug
  HttpPort: 8081
  ReadTimeout: 30
  WriteTimeout: 30
App:
  DefaultPageSize: 15
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: App
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: 902x0210.
  Host: 172.96.239.197:3306
  DBName: blog_service
  TablePrefix: bolg_
  Charset: utf8
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenconns: 30